### ISSUE TITLE
CI/CD

### ISSUE THREAD

**Issue by stechu** [Manta-Network/Manta#13]
Put CI/CD in the pipeline.

**Comment by ghzlatarev** [comment]
Basically check compilation, run tests and run formatting and clippy on the code. 
We could use that as a backbone and build on it. What do you think @grenade  ?

**Comment by stechu** [comment]
Feel like Github action itself would not be sufficient since the resource required to have a reasonably time test would be way beyond the Amazon EC2 tier that Github action uses. We could potentially integrate the CI/CD service that we use with github action though.

**Comment by zhenfeizhang** [comment]
A few more things I can think of

* nightly build (high priority)
* disable CI/CD on all branches except for "manta" and PR -- our build is too slow to allow for CI for all branches (med priority)
* cargo doc test for code quality control -- super low priority

> Maybe benchmark tests needs to be supported in the future.

I think benchmarks should NOT be included in CI/CD.
Our benchmark is even longer than testing because of ZKP.
We should only do benchmarks for performance critical PRs; alternatively we can have two sets of metrics to benchmark, and those ZKP related once will go the the set which we ignore on a routine check.

**Comment by ghzlatarev** [comment]
Besides the Manta repository, do we need workflows in the following :
 * manta-client 
 * pallet-manta-pay
 * manta-node
 
Where else?

**Comment by zhenfeizhang** [comment]
for now we need it for `pallet-manta-pay`. We probably will deprecate `manta-client` and `manta-node`

**Comment by stechu** [comment]
Thanks everyone for making CI/CI work!

**Comment by ghzlatarev** [comment]
Repositories without CI/CD:
* https://github.com/Manta-Network/manta-errors          ---> Added
* https://github.com/Manta-Network/pallet-manta-swap ---> Added

Optimize:
* pallet-manta-pay CI
