### ISSUE TITLE
Manta <> Shawn (August 2)

### ISSUE THREAD

**Issue by stechu** [Manta-Network/Manta#144]
Storage Question:
1. What is a good way to implement a `Vec<Vec<[u8, 32]>` in the ledger storage? for example,
```rust
let coin_shards: Vec<Vec<[u8, 32]> = Vec::new();
```
We would like to support efficiently operations like the following:
```rust
coin_shards[0].append(utxo_bytes);
```
2. Some general idea about the cost of different storage data structure available would be helpful. e.g. the trade offs of using  `Map`, `DoubleMap` and `Vec`. 

The general purpose here is that we would like to avoid any `O(n)` operations in the code.

**Comment by ghzlatarev** [comment]
Governance questions:

1. Any ideas or tips about debugging this ``Storage root must match that calculated`` ? 
   Here's a very similar open issue ---> https://github.com/paritytech/substrate/issues/9423
    In our testnet we use ``rococo-local`` chain spec for ``0.9.8``polkadot version and dependencies.
   Only happens when doing runtime upgrade through democracy. With Sudo there's no problem.
   These suggestions didn't work --> bump the spec_version , added execution=wasm, no change in compiler between upgrades,

2. What are ``WrongProposalLength`` errors and why do they happen when the length argument is calculated automatically ?

3. What is the minimal or most basic governance configuration ?
    It seems I can decouple democracy from council and technical committee , but that requires to use my own pallet.
    Can I just have tech comm and democracy, no council ?
    Can I drop certain functionalities like fast tracking or cancelling selectively ?

4. What is meant by ``along`` in the below statement? How do they work together ?
    "The Technical Committee can, along with the Council, produce emergency referenda," 
    https://remotedesktop.google.com/access/session/9bfd8cdc-0ec7-2772-a76c-2d7fad541525 
    
5. Who can cancel proposals and which proposals ?  
    What about referendums and passed referendums ?
    How are they canceled ?

**Comment by shawntabrizi** [comment]
1. May be caused by this: https://github.com/paritytech/substrate/pull/9399, but generally, if it works for Sudo, democracy should work too. Would be good if you can provide all the stuff needed to reproduce the issue, but first, I would make sure you are using the latest Substrate / Polkadot and test it again.

For questions 2 - 5, i recommend you spend some time really trying to walk through and read the Democracy pallet. If you need, we can dedicate one of our 1:1 meetings on walking through it together.

2. Getting `WrongProposalLength` implies some UI bug. Basically the UI needs to see the side of the storage item you are going to touch, and tell that to the runtime so it can properly weigh the effects.

3. Yes, you should be able to do most of those things. To disable certain calls, you can use call filters to prevent those calls from happening. For setting things up, most of the time `()` should work as a null configuration, but you can also just implement the underlying trait however you like manually. For example selecting specific user accounts to act as those bodies.

4. You should look at how runtime upgrades and things are coordinated on Kusama and Polkadot, but first it starts with Council who can propose a referendum, which goes into democracy, and then the tech committee who can fast track that referendum so it executes faster. If you post these questions into the Polkadot and Kusama direction channels, you will get a lot more information too.

5. Proposals are voted on by council and can be rejected by a majority of users (or however you have configured it). I think only the tech committee can blacklist a referendum if they find it harmful for the network. Again, most of these behaviors are better explained in code than mis translated in text
