### ISSUE TITLE
Investigate why manta parachain produces block so slowly, but acala is more fast than us.

### ISSUE THREAD

**Issue by stechu** [Manta-Network/Manta#147]
This issue would be good case to test integration test from @grenade .

Now, in `manta-acala` XCM experiment, manta parachain (using `manta-pc-dev` config)'s block time is significantly slower than Acala.

**Comment by Dengjianping** [comment]
@stechu 
I just did an experiments on launching manta parachain and acala parachain:
relachain
```
nodes count: 4
```
manta
```
validators count: 2
parachain id: 1999
```
acala
```
validators count: 2
parachain id: 2000
```
Result(almost 5 hours):
```
relachain: 2960 blocks
manta: 1192 blocks
acala: 1456 blocks
```

It appears it's our problem.
I'm going to go through what substrate/polkadot client crates we're depending on.

**Comment by Dengjianping** [comment]
@xialovexia Maybe you can do some more experiments for me if you have time.

**Comment by Dengjianping** [comment]
I just followed statemint' client codes from cumulus branch v0.9.8.
And some experiments have been made.

1. Launch manta and acala.
Result: Our parachain is still having this problem, eventually, the latest block number of manta will fall behind acala's.

2. Just launch manta.
Result: This is pretty weird, the block time is almost expected, 12s per block.
```
start time: 10:03 block number: 0
check time 12:18 block number: 675

duration = 12:18 - 10:03 = 135 minutes

675 * 12 / 60 = 135 minutes
```

**Comment by Dengjianping** [comment]
I went through all the client code base, I found this problem is not related to client implementation.
So I guess it might cause by runtime, I compared both `statemint`(v0.9.8) and `manta-pc` runtime, the big difference is this line of code:
`statemint`
```rust
ParachainSystem: cumulus_pallet_parachain_system::{Pallet, Call, Config, Storage, Inherent, Event<T>} = 1,
```

`manta-pc`
```rust
ParachainSystem: cumulus_pallet_parachain_system::{Pallet, Call, Storage, Inherent, Event<T>} = 1,
```
In `statemint`, they enables the configuration of `ParachainSystem`, and acala does as well.

So, I followed their configuration, and add this line to our chain spec:
```rust
parachain_system: Default::default(),
```

Finally, the block time of our parachain is faster than acala's.

Related issue:  https://github.com/paritytech/cumulus/issues/479
Related code: https://github.com/paritytech/cumulus/blob/polkadot-v0.9.8/pallets/parachain-system/src/lib.rs#L593
