### ISSUE TITLE
CLA should be triggered if any contribution from community

### ISSUE THREAD

**Issue by Dengjianping** [Manta-Network/Manta#362]
Currently, we have a contribution from community, #361.
But his pr didn't trigger our CI, we have to approve it manually.
Not sure CLA will fix it.

**Comment by nicobao** [comment]
Hi,

Thanks for making Manta Free software.

Please do not enforce CLA otherwise nobody will ever be willing to contribute to your open-source project.

CLA is the cancer of open-source. It basically grants all copyrights of contributors to one single-organization - you - that can change the license to whichever you fancy at any time, including going proprietary. That's exactly what Oracle did with MySQL and look where it got them...

Adopting CLA is the best choice you can make to add more barriers for new developers to step in. You want to create an inclusive and open community instead, otherwise why going open-source at all? It's already hard enough to attract them.

Your PR mentions the SAP CLA. Now, look at one of the first line of the contract:

> Copyright License. You hereby grant, and agree to grant, to SAP a non-exclusive, perpetual, irrevocable, worldwide, fully-paid, royalty-free, transferable copyright license to reproduce, prepare derivative works of, publicly display, publicly perform, and distribute your Contributions and such derivative works, with the right to sublicense the foregoing rights through multiple tiers of sublicensees.

Use a Developer Certificate of Origin (DCO) instead, it's just fine. That's what Linux and GitLab and many others use: https://about.gitlab.com/blog/2017/11/01/gitlab-switches-to-dco-license/#why-the-change

Or if you want to go contract full-in and want to keep the possibility to change the open-source license to another one in the future while respecting contributors' copyrights, go for the Fiduciary License Agreement (FLA), used by KDE: https://fsfe.org/activities/fla/fla.en.html 

Some background info: https://ben.balter.com/2018/01/02/why-you-probably-shouldnt-add-a-cla-to-your-open-source-project/

**Comment by stechu** [comment]
Thanks for the suggestion, @nicobao 
Our goal is to keep Manta as Free and Open Sourced Software (Free means freedom here).
@rishabhfsd Can you add a DCO instead?

**Comment by rishabhfsd** [comment]
sure @stechu I'll integrate DCO instead. Thank you for suggestion @nicobao

**Comment by ghzlatarev** [comment]
Please add a second step conditional on the DCO check failing. to write a comment in the PR with all the instructions. No one is going to read the CI output.

**Comment by rishabhfsd** [comment]
@ghzlatarev will find the solution for that.
