### ISSUE TITLE
xcm config: fees too high?

### ISSUE THREAD

**Issue by gilescope** [Manta-Network/Manta#492]
It's currently using identity fee for xcm:

type Trader = UsingComponents<IdentityFee<Balance>, ..>;

This is likely to mean the same fees as the relay chain. In all likelyhood parachains don't need as high fees.

https://github.com/paritytech/cumulus/issues/920 - we noticed this on statemint. Encointer have also recently tweaked their code to not use `IdentityFee<Balance>`. I suspect you might want to do the same.

**Comment by ghzlatarev** [comment]
Thanks for reporting.

**Comment by ghzlatarev** [comment]
Thanks for reporting again.
We actually don't use `type Trader = UsingComponents<IdentityFee, ..>;` for our live XCM code (Dolphin & Calamari).
For their Xcm config we manually set a `units_per_sec` value for each asset that's used in the `buy_weight` calculation. That's how we control the amount of fees paid, so this issue is not relevant.
 `type Trader = UsingComponents<IdentityFee, ..>;` is only used in the Manta runtime code, which is not live and not up to date atm.
