### ISSUE TITLE
Beef up benchmarking machine

### ISSUE THREAD

**Issue by ghzlatarev** [Manta-Network/Manta#768]
Currently our bare metal benchmark machine c5d.metal is actually less performant than the substrate reference hardware that we recommend:
```
+----------+----------------+--------------+--------------+-------------------+
| Category | Function       | Score        | Minimum      | Result            |
+=============================================================================+
| CPU      | BLAKE2-256     | 894.04 MiB/s | 1.00 GiB/s   | ❌ Fail ( 86.9 %) |
|----------+----------------+--------------+--------------+-------------------|
| CPU      | SR25519-Verify | 577.11 KiB/s | 666.00 KiB/s | ❌ Fail ( 86.7 %) |
|----------+----------------+--------------+--------------+-------------------|
| Memory   | Copy           | 4.81 GiB/s   | 14.32 GiB/s  | ❌ Fail ( 33.6 %) |
|----------+----------------+--------------+--------------+-------------------|
| Disk     | Seq Write      | 142.29 MiB/s | 450.00 MiB/s | ❌ Fail ( 31.6 %) |
|----------+----------------+--------------+--------------+-------------------|
| Disk     | Rnd Write      | 64.05 MiB/s  | 200.00 MiB/s | ❌ Fail ( 32.0 %) |
+----------+----------------+--------------+--------------+-------------------+
```

Rebenchmarking with a beefier machine that fits more closely to the reference hardware, will drop our runtime weights and improve performance. Low hanging fruit.

**Comment by Garandor** [comment]
@ryanlin-tech could you help us find a machine somewhere that closely matches the above specs?

**Comment by Garandor** [comment]
@ryanlin-tech any updates on this topic?

**Comment by ryanlin-tech** [comment]
yes, i had a discussion with rob yesterday, he will comment here.

**Comment by grenade** [comment]
reference hardware (https://wiki.polkadot.network/docs/maintain-guides-how-to-validate-polkadot#reference-hardware):

- **CPU**
  - x86-64 compatible;
  - Intel Ice Lake, or newer (Xeon or Core series); AMD Zen3, or newer (EPYC or Ryzen);
  - 4 physical cores @ 3.4GHz;
  - Simultaneous multithreading disabled (Hyper-Threading on Intel, SMT on AMD);
  - Prefer single-threaded performance over higher cores count. A comparison of single-threaded performance can be found [here](https://www.cpubenchmark.net/singleThread.html).
- **Storage**
  - An NVMe SSD of 1 TB (As it should be reasonably sized to deal with blockchain growth). An estimation of current chain snapshot sizes can be found [here](https://paranodes.io/DBSize). In general, the latency is more important than the throughput.
- **Memory**
  - 16GB DDR4 ECC.
- **System**
  - Linux Kernel 5.16 or newer.
- **Network**
  - The minimum symmetric networking speed is set to 500 Mbit/s (= 62.5 MB/s). This is required to support a large number of parachains and allow for proper congestion control in busy network situations.

aws ec2 c5d.metal looks pretty good beside these requirements, not least due to having an [Intel Xeon Platinum 8275L](https://www.intel.com/content/www/us/en/products/sku/192475/intel-xeon-platinum-8276l-processor-38-5m-cache-2-20-ghz/specifications.html) cpu with 28 physical cores (base 2.2ghz, turbo 4 ghz).

i suspect the devil, as always, is in the detail.

the part of the reference hardware spec that catches my eye is this:

> Simultaneous multithreading disabled (Hyper-Threading on Intel, SMT on AMD)

is this something the benchmarking tests are [taking a stab](https://www.baeldung.com/linux/disable-hyperthreading) at achieving or has it been overlooked?

if we want to achieve disabled hyperthreading or disabled simultaneous multithreading at an infra level (instead of during runtime), i think we'd have to rule out third-party providers altogether. none of ours give bios access.

i could add such a system to one of the physical racks i run in bulgaria but we'd need to purchase the physical hardware in order to go that route.

let me know if you have already been down the route of attempting to disable smt at runtime without success and i'll start shopping for hardware.
