### ISSUE TITLE
Figure out whether `OnTimestampSet = Aura` affect us

### ISSUE THREAD

**Issue by Dengjianping** [Manta-Network/Manta#901]
It happened to cumulus `release-v0.9.320`.
Related pr: https://github.com/paritytech/cumulus/pull/1877

@Garandor

**Comment by Garandor** [comment]
I suppose a description in that linked PR would've been helpful, but anyways, 

It's used for a sanity check by Aura in https://github.com/paritytech/substrate/blob/polkadot-v0.9.26/frame/aura/src/lib.rs#L299

Closing as WONTFIX as it does not affect us:
1. We no longer use Aura slots
2. Nimbus slots are defined by `RelaychainBlockNumberProvider` instead of `cumulus_pallet_parachain_system::pallet_timestamp` so they don't depend on RTC time

Thanks for raising this @Dengjianping
